CLD-264-Update-PD-analytics-param-in-asset-URL
cloudinary/cloudinary_sfcc_pagedesigner pull request #60
Opened 2023-12-18 08:07 UTC by asad-rafter

2023-12-18 13:22 UTC, yuval-cloudinary requested changes
Do we need to update 'getBreackpoints' as well?

2023-12-19 10:15 UTC, yuval-cloudinary approved these changes

2024-01-01 17:05 UTC, yuval-cloudinary requested changes

2024-01-01 17:05 UTC, yuval-cloudinary commented on cartridges/int_cloudinary_pd/cartridge/experience/components/assets/mediaLibraryVideo.js
> +        conf.sourceConfig.queryParams = { '_i': 'AH' };
Use the tracking param to avoid having the tag redefined:
conf.sourceConfig.queryParams = {[c.substring(1).split('=')[0]] : c.substring(1).split('=')[1]};

2024-01-02 08:43 UTC, asad-rafter commented on cartridges/int_cloudinary_pd/cartridge/experience/components/assets/mediaLibraryVideo.js
> +        conf.sourceConfig.video.url = conf.sourceConfig.video.url + constants.CLD_TRACKING_PARAM;
If I understand correctly, we don't need to have tracking param with video URL?

2024-01-02 10:57 UTC, yuval-cloudinary commented on cartridges/int_cloudinary_pd/cartridge/experience/components/assets/mediaLibraryVideo.js
> +        conf.sourceConfig.video.url = conf.sourceConfig.video.url + constants.CLD_TRACKING_PARAM;
When a video is played with the Cloudinary Video Player (like in this case), then the Video Player adds the tag using the `queryParams` configuration

2024-01-02 15:25 UTC, yuval-cloudinary approved these changes

2024-01-31 07:01 UTC, merged