CLD-263-update-page-designer-user-agent
cloudinary/cloudinary_sfcc_pagedesigner pull request #61
Opened 2024-01-01 08:57 UTC by asad-rafter

2024-01-01 09:48 UTC, yuval-cloudinary requested changes

2024-01-01 09:48 UTC, yuval-cloudinary commented on cartridges/int_cloudinary_pd/cartridge/experience/utils/constants.js
> +    CLD_TRACKING_PARAM: '?_i=AH',
This seems to have leaked from cld-264, please remove

2024-01-01 09:48 UTC, yuval-cloudinary commented on cartridges/int_cloudinary_pd/cartridge/experience/utils/constants.js
> +    API_TRACKING_PARAM: 'CloudinarySalesForcePageDesigner/20.0.4 (CommerceCloud ' + System.compatibilityMode + ') Architecture SFCC'
We requested the following user-agent:
CloudinarySalesForcePageDesigner/<cartridge ver> (<platform> <ver>) <SFCC arch>

Please have the cartridge version and the architecture taken from the environment (not hard-coded)

2024-01-01 10:14 UTC, asad-rafter commented on cartridges/int_cloudinary_pd/cartridge/experience/utils/constants.js
> +    API_TRACKING_PARAM: 'CloudinarySalesForcePageDesigner/20.0.4 (CommerceCloud ' + System.compatibilityMode + ') Architecture SFCC'
do you want me to create custom preference for this?

2024-01-01 10:28 UTC, yuval-cloudinary commented on cartridges/int_cloudinary_pd/cartridge/experience/utils/constants.js
> +    API_TRACKING_PARAM: 'CloudinarySalesForcePageDesigner/20.0.4 (CommerceCloud ' + System.compatibilityMode + ') Architecture SFCC'
This is not a user-preference, so please keep it in the code.
However, I expect the cartridge version to reflect the cartridge version, not a hard-coded 20.0.4.
Similarly, the system architecture is SFRA/SG/PWA/etc... not a hard-coded "Architecture SFCC"

2024-01-01 12:48 UTC, asad-rafter commented on cartridges/int_cloudinary_pd/cartridge/experience/utils/constants.js
> +    API_TRACKING_PARAM: 'CloudinarySalesForcePageDesigner/20.0.4 (CommerceCloud ' + System.compatibilityMode + ') Architecture SFCC'
From where do you want me to get the cartridge version value and system architecture?

2024-01-01 14:51 UTC, yuval-cloudinary commented
The caryridge has the version in multiple places, please use the most
appropiate. For the architecture, maybe SFCC docs?

On Mon, Jan 1, 2024, 14:48 asad-rafter ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In cartridges/int_cloudinary_pd/cartridge/experience/utils/constants.js
> <https://github.com/cloudinary/cloudinary_sfcc_pagedesigner/pull/61#discussion_r1439022011>
> :
>
> > @@ -0,0 +1,6 @@
> +var System = require('dw/system/System');
> +
> +module.exports.cloudinaryConstants = {
> +    CLD_TRACKING_PARAM: '?_i=AH',
> +    API_TRACKING_PARAM: 'CloudinarySalesForcePageDesigner/20.0.4 (CommerceCloud ' + System.compatibilityMode + ') Architecture SFCC'
>
> From where do you want me to get the cartridge version value and system
> architecture?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/cloudinary/cloudinary_sfcc_pagedesigner/pull/61#discussion_r1439022011>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALEL2NBQW4MA7EG72D7LXLDYMKWBHAVCNFSM6AAAAABBI3XTG6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOOJZG44TMOJZHE>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***
> com>
>

2024-01-02 12:56 UTC, asad-rafter commented on cartridges/int_cloudinary_pd/cartridge/experience/utils/constants.js
> +    API_TRACKING_PARAM: 'CloudinarySalesForcePageDesigner/20.0.4 (CommerceCloud ' + System.compatibilityMode + ') Architecture SFCC'
For the cartridge version we have fixed that, but for SFCC architecture there is no way in SF to get the site architecture if its SFRA/SG/PWA, the only thing we can do is to make a site preference and set and read value from there.

2024-01-02 13:07 UTC, yuval-cloudinary commented on cartridges/int_cloudinary_pd/cartridge/experience/utils/constants.js
> +    API_TRACKING_PARAM: 'CloudinarySalesForcePageDesigner/20.0.4 (CommerceCloud ' + System.compatibilityMode + ') Architecture SFCC'
@asad-rafter I see. Please put there a hard-coded "SFPD", e.g.:
CloudinarySalesForcePageDesigner/\<cartridge ver> (\<platform> \<ver>) SFPD

2024-01-02 15:21 UTC, yuval-cloudinary approved these changes

2024-01-08 08:47 UTC, yuval-cloudinary approved these changes

2024-01-31 07:07 UTC, merged