CLD-293
cloudinary/cloudinary_sfcc_pagedesigner pull request #70
Opened 2024-03-21 11:23 UTC by asad-rafter

2024-03-21 12:12 UTC, yuval-cloudinary requested changes

2024-03-21 12:12 UTC, yuval-cloudinary commented on cartridges/bm_cloudinary_pd/cartridge/scripts/cloudinary/cloudinaryApi.js
> +var constants = require('*/cartridge/experience/utils/cloudinaryConstants').cloudinaryConstants;
do we have to start with an asterisk (*)?
even with other Cloudinary cartridges I wouldn't want any confusion

2024-03-21 12:12 UTC, yuval-cloudinary commented on cartridges/bm_cloudinary_pd/cartridge/scripts/cloudinary/cloudinaryApi.js
> +        cloudinaryService.setURL(url + '/' + fileType + '/' + callType);
Looks much better!

2024-03-22 06:23 UTC, asad-rafter commented on cartridges/bm_cloudinary_pd/cartridge/scripts/cloudinary/cloudinaryApi.js
> +var constants = require('*/cartridge/experience/utils/cloudinaryConstants').cloudinaryConstants;
@Yuval Papish The file exists in a different cartridge like in “int_cloudinary_pd“ and it's being used in “bm_cloudinary_pd“, in this case, we must have to use “*“, otherwise it will not require the file.

2024-03-26 07:35 UTC, yuval-cloudinary approved these changes

2024-03-28 12:16 UTC, yuval-cloudinary approved these changes

2024-04-01 07:27 UTC, merged