fixed console errors, added shrinkwrap.js
cloudinary/cloudinary_sfcc_pagedesigner pull request #80
Opened 2024-06-20 10:44 UTC by asad-rafter

2024-06-20 10:55 UTC, yuval-cloudinary requested changes

2024-06-20 10:55 UTC, yuval-cloudinary commented on cartridges/int_cloudinary_pd/cartridge/templates/default/experience/components/assets/cloudinaryImage.isml
> +      var src = 'https://unpkg.com/cloudinary-core/cloudinary-core-shrinkwrap.min.js';
The coresite cartridge uses "https://unpkg.com/cloudinary-core@2.13.0/cloudinary-core-shrinkwrap.js" and that is configurable. Let's keep it consistent, esp. as a page can contain code from both cartridges

2024-06-20 10:55 UTC, yuval-cloudinary commented on cartridges/int_cloudinary_pd/cartridge/templates/default/experience/components/assets/cloudinaryImage.isml
> +   if (script === null) {
can we remove the leading space?

2024-06-20 10:55 UTC, yuval-cloudinary commented on cartridges/int_cloudinary_pd/cartridge/templates/default/experience/components/assets/cloudinaryVideo.isml
> +	var src = 'https://unpkg.com/cloudinary-video-player@'+verJson.videoPlayerVersion+'/dist/cld-video-player.min.css';
please properly ident with spaces

2024-06-20 10:55 UTC, yuval-cloudinary commented on cartridges/int_cloudinary_pd/cartridge/templates/default/experience/components/assets/cloudinaryVideo.isml
> +	src = 'https://unpkg.com/cloudinary-video-player@'+verJson.videoPlayerVersion+'/dist/cld-video-player.min.js';
please properly ident with spaces

2024-06-20 10:55 UTC, yuval-cloudinary commented on cartridges/int_cloudinary_pd/cartridge/templates/default/experience/components/assets/cloudinaryVideo.isml
> +  const shrinkWrapJs = document.querySelector('script[src="https://unpkg.com/cloudinary-core/cloudinary-core-shrinkwrap.min.js"]');
The coresite cartridge uses "https://unpkg.com/cloudinary-core@2.13.0/cloudinary-core-shrinkwrap.js" and that is configurable. Let's keep it consistent, esp. as a page can contain code from both cartridges

2024-06-20 10:55 UTC, yuval-cloudinary commented on example/cld_custom_i9n/cartridge/templates/default/experience/components/assets/example.isml
> +      var src = 'https://unpkg.com/cloudinary-core/cloudinary-core-shrinkwrap.min.js';
The coresite cartridge uses "https://unpkg.com/cloudinary-core@2.13.0/cloudinary-core-shrinkwrap.js" and that is configurable. Let's keep it consistent, esp. as a page can contain code from both cartridges

2024-06-20 10:55 UTC, yuval-cloudinary commented on example/cld_custom_i9n/cartridge/templates/default/experience/components/assets/example.isml
> +   if (script === null) {
leading space

2024-06-20 10:55 UTC, yuval-cloudinary commented on example/cld_custom_i9n/cartridge/templates/default/experience/components/assets/videoExample.isml
> +      const shrinkWrapJs = document.querySelector('script[src="https://unpkg.com/cloudinary-core/cloudinary-core-shrinkwrap.min.js"]');
The coresite cartridge uses "https://unpkg.com/cloudinary-core@2.13.0/cloudinary-core-shrinkwrap.js" and that is configurable. Let's keep it consistent, esp. as a page can contain code from both cartridges

2024-06-20 12:29 UTC, asad-rafter commented on cartridges/int_cloudinary_pd/cartridge/templates/default/experience/components/assets/cloudinaryImage.isml
> +      var src = 'https://unpkg.com/cloudinary-core/cloudinary-core-shrinkwrap.min.js';
We need to create separate custom preferences for these like we did for the core cartridge, we cannot use existing ones because there is a possibility that someone will install the PD cartridge only not SFCC.

2024-06-20 12:29 UTC, asad-rafter commented on cartridges/int_cloudinary_pd/cartridge/templates/default/experience/components/assets/cloudinaryImage.isml
> +   if (script === null) {
sure

2024-06-20 12:30 UTC, asad-rafter commented on example/cld_custom_i9n/cartridge/templates/default/experience/components/assets/example.isml
> +      var src = 'https://unpkg.com/cloudinary-core/cloudinary-core-shrinkwrap.min.js';
We need to create separate custom preferences for these like we did for the core cartridge, we cannot use existing ones because there is a possibility that someone will install the PD cartridge only not SFCC.

2024-06-20 12:30 UTC, asad-rafter commented on example/cld_custom_i9n/cartridge/templates/default/experience/components/assets/videoExample.isml
> +      const shrinkWrapJs = document.querySelector('script[src="https://unpkg.com/cloudinary-core/cloudinary-core-shrinkwrap.min.js"]');
We need to create separate custom preferences for these like we did for the core cartridge, we cannot use existing ones because there is a possibility that someone will install the PD cartridge only not SFCC.

2024-06-20 12:50 UTC, yuval-cloudinary commented on cartridges/int_cloudinary_pd/cartridge/templates/default/experience/components/assets/cloudinaryImage.isml
> +      var src = 'https://unpkg.com/cloudinary-core/cloudinary-core-shrinkwrap.min.js';
sure, please proceed

2024-06-20 14:55 UTC, yuval-cloudinary commented on example/cld_custom_i9n/cartridge/templates/default/experience/components/assets/videoExample.isml
>  <!--- TEMPLATENAME: example.isml --->
Please convert to iscomment

2024-06-20 14:55 UTC, yuval-cloudinary commented on example/cld_custom_i9n/cartridge/templates/default/experience/components/assets/videoExample.isml
>  	var verJson = require('*/cartridge/scripts/cloudinary/version.json');
Not used, please remove

2024-06-20 14:59 UTC, yuval-cloudinary commented on example/cld_custom_i9n/cartridge/templates/default/experience/components/assets/example.isml
>  <!--- TEMPLATENAME: example.isml --->
Please use iscomment

2024-06-20 14:59 UTC, yuval-cloudinary commented on example/cld_custom_i9n/cartridge/templates/default/experience/components/assets/example.isml
> +    var verJson = require('*/cartridge/scripts/cloudinary/version.json');
Please remove unless used

2024-06-20 15:09 UTC, yuval-cloudinary commented on metadata/cloudinary_pagedesigner_metadata.zip
You are using an old version of metadata. Please copy from zzgt007, and modify accordingly. Remember to remove the password

2024-06-20 15:13 UTC, asad-rafter commented on metadata/cloudinary_pagedesigner_metadata.zip
I believe its the updated one, could you please refer to something you see older so I can compare?

2024-06-20 15:24 UTC, asad-rafter commented on cartridges/int_cloudinary_pd/cartridge/templates/default/experience/components/assets/cloudinaryImage.isml
> +      var src = 'https://unpkg.com/cloudinary-core/cloudinary-core-shrinkwrap.min.js';
fixed

2024-06-20 15:24 UTC, asad-rafter commented on cartridges/int_cloudinary_pd/cartridge/templates/default/experience/components/assets/cloudinaryImage.isml
> +   if (script === null) {
fixed

2024-06-20 15:24 UTC, asad-rafter commented on cartridges/int_cloudinary_pd/cartridge/templates/default/experience/components/assets/cloudinaryVideo.isml
> +	var src = 'https://unpkg.com/cloudinary-video-player@'+verJson.videoPlayerVersion+'/dist/cld-video-player.min.css';
fixed

2024-06-20 15:24 UTC, asad-rafter commented on cartridges/int_cloudinary_pd/cartridge/templates/default/experience/components/assets/cloudinaryVideo.isml
> +	src = 'https://unpkg.com/cloudinary-video-player@'+verJson.videoPlayerVersion+'/dist/cld-video-player.min.js';
fixed

2024-06-20 15:24 UTC, asad-rafter commented on cartridges/int_cloudinary_pd/cartridge/templates/default/experience/components/assets/cloudinaryVideo.isml
> +  const shrinkWrapJs = document.querySelector('script[src="https://unpkg.com/cloudinary-core/cloudinary-core-shrinkwrap.min.js"]');
fixed

2024-06-20 15:24 UTC, asad-rafter commented on example/cld_custom_i9n/cartridge/templates/default/experience/components/assets/example.isml
> +      var src = 'https://unpkg.com/cloudinary-core/cloudinary-core-shrinkwrap.min.js';
fixed

2024-06-20 15:25 UTC, asad-rafter commented on example/cld_custom_i9n/cartridge/templates/default/experience/components/assets/example.isml
> +   if (script === null) {
fixed

2024-06-20 15:25 UTC, yuval-cloudinary commented on metadata/cloudinary_pagedesigner_metadata.zip
I see that CloudinaryPageDesignerUseSha256 disappeared, and that the <password> definition doesn't look as it used to

2024-06-20 15:25 UTC, asad-rafter commented on example/cld_custom_i9n/cartridge/templates/default/experience/components/assets/videoExample.isml
> +      const shrinkWrapJs = document.querySelector('script[src="https://unpkg.com/cloudinary-core/cloudinary-core-shrinkwrap.min.js"]');
fixed

2024-06-20 15:25 UTC, asad-rafter commented on example/cld_custom_i9n/cartridge/templates/default/experience/components/assets/videoExample.isml
>  <!--- TEMPLATENAME: example.isml --->
fixed

2024-06-20 15:25 UTC, asad-rafter commented on example/cld_custom_i9n/cartridge/templates/default/experience/components/assets/videoExample.isml
>  	var verJson = require('*/cartridge/scripts/cloudinary/version.json');
fixed

2024-06-20 15:25 UTC, asad-rafter commented on example/cld_custom_i9n/cartridge/templates/default/experience/components/assets/example.isml
>  <!--- TEMPLATENAME: example.isml --->
fixed

2024-06-20 15:25 UTC, asad-rafter commented on example/cld_custom_i9n/cartridge/templates/default/experience/components/assets/example.isml
> +    var verJson = require('*/cartridge/scripts/cloudinary/version.json');
fixed

2024-06-20 15:25 UTC, asad-rafter commented on cartridges/int_cloudinary_pd/cartridge/templates/default/experience/components/assets/cloudinaryImage.isml
> +    pdict.viewmodel.CLDPDVideoPlayerJSURL = sitePref.CLDPDVideoPlayerJSURL;
fixed

2024-06-20 15:27 UTC, asad-rafter commented on metadata/cloudinary_pagedesigner_metadata.zip
should I get it from the master branch and update it?

2024-06-20 15:29 UTC, asad-rafter commented on metadata/cloudinary_pagedesigner_metadata.zip
password hash removed as part of it https://github.com/cloudinary/cloudinary_sfcc_pagedesigner/pull/78#discussion_r1638391173

2024-06-20 15:38 UTC, asad-rafter commented on metadata/cloudinary_pagedesigner_metadata.zip
CloudinaryPageDesignerUseSha256 is remove as part of https://github.com/cloudinary/cloudinary_sfcc_pagedesigner/pull/78

2024-06-20 15:53 UTC, yuval-cloudinary commented on metadata/cloudinary_pagedesigner_metadata.zip
Was it removed intentionally or accidentally? I don't see it being used in the code, I guess it is a good change

2024-06-20 16:02 UTC, yuval-cloudinary commented on metadata/cloudinary_pagedesigner_metadata.zip
Please use 'https://unpkg.com/cloudinary-core@2.13.0/cloudinary-core-shrinkwrap.js' for CLDPDShrinkwrapJSURL, exactly as it is in the coresite cartridge

2024-06-21 06:58 UTC, asad-rafter commented on metadata/cloudinary_pagedesigner_metadata.zip
It was intentionally, when you asked to removed password hash, we noticed this as well as its not used anywhere, so we removed it :)

2024-06-21 07:00 UTC, asad-rafter commented on metadata/cloudinary_pagedesigner_metadata.zip
fixed

2024-06-24 08:05 UTC, yuval-cloudinary approved these changes

2024-06-24 08:08 UTC, merged