cartridge improvements
cloudinary/cloudinary_sfcc_pagedesigner pull request #87
Opened 2024-08-06 10:23 UTC by asad-rafter

2024-08-06 13:29 UTC, yuval-cloudinary requested changes

2024-08-06 13:29 UTC, yuval-cloudinary commented on cartridges/int_cloudinary_pd/cartridge/templates/default/experience/components/assets/cloudinaryImage.isml
>      pdict.viewmodel.CLDPDShrinkwrapJSURL = sitePref.CLDPDShrinkwrapJSURL;
please remove all references to the shrinkwrap lib, as it is not used anywhere

2024-08-06 14:42 UTC, asad-rafter commented on cartridges/int_cloudinary_pd/cartridge/experience/components/assets/mediaLibraryVideo.js
>  var currentSite = require('dw/system/Site').getCurrent();
It is used in multiple functions, that's why  we make it global.

2024-08-06 14:43 UTC, asad-rafter commented on cartridges/int_cloudinary_pd/cartridge/experience/components/assets/mediaLibrary.js
>  var currentSite = require('dw/system/Site').getCurrent();
It is used in multiple functions, that's why we make it global.

2024-08-06 14:52 UTC, yuval-cloudinary commented on cartridges/int_cloudinary_pd/cartridge/experience/components/assets/mediaLibraryVideo.js
>  var currentSite = require('dw/system/Site').getCurrent();
It is still a performance penalty for functions that don't use it. Please have it only where it is needed, in the smallest scope that makes sense

2024-08-06 14:52 UTC, yuval-cloudinary commented on cartridges/int_cloudinary_pd/cartridge/experience/components/assets/mediaLibraryVideo.js
>  var constants = require('~/cartridge/experience/utils/cloudinaryPDConstants').cloudinaryPDConstants;
It is still a performance penalty for functions that don't use it. Please have it only where it is needed, in the smallest scope that makes sense

2024-08-06 14:52 UTC, yuval-cloudinary commented on cartridges/int_cloudinary_pd/cartridge/experience/components/assets/mediaLibrary.js
>  var currentSite = require('dw/system/Site').getCurrent();
It is still a performance penalty for functions that don't use it. Please have it only where it is needed, in the smallest scope that makes sense

2024-08-06 14:53 UTC, yuval-cloudinary commented on cartridges/int_cloudinary_pd/cartridge/static/default/js/cloudinaryVideos.js
> +        cld = cloudinary.Cloudinary.new(conf);
window.cld of course.
also check for other locations where 'cld' is used without explicit binding

2024-08-06 14:55 UTC, asad-rafter commented on cartridges/int_cloudinary_pd/cartridge/templates/default/experience/components/assets/cloudinaryImage.isml
>      pdict.viewmodel.CLDPDShrinkwrapJSURL = sitePref.CLDPDShrinkwrapJSURL;
we have added shrink wrap recently as part of this 
https://github.com/cloudinary/cloudinary_sfcc_pagedesigner/pull/80/commits/b12f2f08c4316550f8255e5515909163c361a943

2024-08-06 15:03 UTC, yuval-cloudinary commented on cartridges/int_cloudinary_pd/cartridge/templates/default/experience/components/assets/cloudinaryImage.isml
>      pdict.viewmodel.CLDPDShrinkwrapJSURL = sitePref.CLDPDShrinkwrapJSURL;
which JIRA issue was adding the shrinkwrap?
PageDesigner itself doesn't use it for sure, maybe it was needed for the old video player?

2024-08-19 08:13 UTC, yuval-cloudinary commented on cartridges/int_cloudinary_pd/cartridge/experience/components/assets/mediaLibrary.js
>  }
still open

2024-08-19 08:14 UTC, yuval-cloudinary commented on cartridges/int_cloudinary_pd/cartridge/templates/default/experience/components/assets/cloudinaryImage.isml
>      pdict.viewmodel.CLDPDShrinkwrapJSURL = sitePref.CLDPDShrinkwrapJSURL;
still open

2024-08-19 08:14 UTC, yuval-cloudinary commented on cartridges/int_cloudinary_pd/cartridge/templates/default/experience/components/assets/cloudinaryImage.isml
>      pdict.viewmodel.CLDPDVideoPlayerJSURL = sitePref.CLDPDVideoPlayerJSURL;
still open

2024-08-19 10:51 UTC, yuval-cloudinary commented on cartridges/int_cloudinary_pd/cartridge/templates/default/experience/components/assets/cloudinaryImage.isml
>      pdict.viewmodel.CLDPDVideoPlayerJSURL = sitePref.CLDPDVideoPlayerJSURL;
@asad-rafter It seems you answered another question. Here, I asked "why is the videoplayer defined in the cloudinaryImage.ISML?"

2024-08-19 10:53 UTC, yuval-cloudinary commented on cartridges/int_cloudinary_pd/cartridge/templates/default/experience/components/assets/cloudinaryImage.isml
>      pdict.viewmodel.CLDPDShrinkwrapJSURL = sitePref.CLDPDShrinkwrapJSURL;
cld-304 has PR#81, not PR#80
JIRA has links to comments, can you please share the link to the comment on JIRA?

2024-08-19 10:54 UTC, yuval-cloudinary commented on cartridges/int_cloudinary_pd/cartridge/templates/default/experience/components/assets/cloudinaryImage.isml
>      pdict.viewmodel.CLDPDShrinkwrapJSURL = sitePref.CLDPDShrinkwrapJSURL;
In addition, the commit you shared leads me to PR#78

2024-08-19 10:55 UTC, asad-rafter commented on cartridges/int_cloudinary_pd/cartridge/templates/default/experience/components/assets/cloudinaryImage.isml
>      pdict.viewmodel.CLDPDShrinkwrapJSURL = sitePref.CLDPDShrinkwrapJSURL;
![Uploading image.png…]()

2024-08-19 10:56 UTC, asad-rafter commented on cartridges/int_cloudinary_pd/cartridge/templates/default/experience/components/assets/cloudinaryImage.isml
>      pdict.viewmodel.CLDPDShrinkwrapJSURL = sitePref.CLDPDShrinkwrapJSURL;
![image](https://github.com/user-attachments/assets/d36ea9f4-4c5a-49c7-a4d4-71e57d6d2781)

2024-08-19 10:59 UTC, asad-rafter commented on cartridges/int_cloudinary_pd/cartridge/templates/default/experience/components/assets/cloudinaryImage.isml
>      pdict.viewmodel.CLDPDVideoPlayerJSURL = sitePref.CLDPDVideoPlayerJSURL;
We are getting the video player URL to compare with shrink wrap. If the video player URL doesn't exist only in that case we are including shrink wrap URL in DOM, at line 23

2024-08-19 11:00 UTC, asad-rafter commented on cartridges/int_cloudinary_pd/cartridge/templates/default/experience/components/assets/cloudinaryImage.isml
>      pdict.viewmodel.CLDPDShrinkwrapJSURL = sitePref.CLDPDShrinkwrapJSURL;
![image](https://github.com/user-attachments/assets/3ca365d2-bf36-4b89-afd8-3ec0b03e5801)

2024-08-19 11:02 UTC, yuval-cloudinary commented on cartridges/int_cloudinary_pd/cartridge/templates/default/experience/components/assets/cloudinaryImage.isml
>      pdict.viewmodel.CLDPDVideoPlayerJSURL = sitePref.CLDPDVideoPlayerJSURL;
Thanks, so please remove the shrinkwrap and the check for the Video Player, and deploy

2024-08-19 11:03 UTC, yuval-cloudinary commented on cartridges/int_cloudinary_pd/cartridge/templates/default/experience/components/assets/cloudinaryImage.isml
>      pdict.viewmodel.CLDPDShrinkwrapJSURL = sitePref.CLDPDShrinkwrapJSURL;
Thanks, so please remove the shrinkwrap and we will test it again

2024-08-19 11:05 UTC, asad-rafter commented on cartridges/int_cloudinary_pd/cartridge/templates/default/experience/components/assets/cloudinaryImage.isml
>      pdict.viewmodel.CLDPDVideoPlayerJSURL = sitePref.CLDPDVideoPlayerJSURL;
sure

2024-08-19 11:05 UTC, asad-rafter commented on cartridges/int_cloudinary_pd/cartridge/templates/default/experience/components/assets/cloudinaryImage.isml
>      pdict.viewmodel.CLDPDShrinkwrapJSURL = sitePref.CLDPDShrinkwrapJSURL;
sure

2024-08-21 19:07 UTC, yuval-cloudinary approved these changes

2024-08-26 15:19 UTC, merged